// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SagradaFamilia.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SagradaFamilia.Infrastructure.Persistence.Migrations.Postgres
{
    [DbContext(typeof(PostgresAppDbContext))]
    partial class PostgresAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Acciones", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EdadMinimaMeses")
                        .HasColumnType("integer");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Recomendacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Eliminado");

                    b.ToTable("Alimentos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClavePrimaria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ValoresAntiguos")
                        .HasColumnType("text");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Tabla");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.CatalogoValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("Tipo", "Codigo")
                        .IsUnique()
                        .HasFilter("\"Eliminado\" = false");

                    b.ToTable("CatalogosValor", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.CategoriaAlimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.ToTable("CategoriasAlimentos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CitaOrigenId")
                        .HasColumnType("integer");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text");

                    b.Property<int>("NinoId")
                        .HasColumnType("integer");

                    b.Property<string>("NotasConsulta")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CitaOrigenId");

                    b.HasIndex("Eliminado");

                    b.HasIndex("NinoId");

                    b.HasIndex("MedicoId", "FechaHora")
                        .IsUnique()
                        .HasFilter("\"Estado\" != 5 AND \"Estado\" != 6 AND \"Eliminado\" = false");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Evolucion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Indicaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NinoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("Eliminado");

                    b.HasIndex("MedicoId");

                    b.HasIndex("NinoId");

                    b.ToTable("Consultas", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.EventoCorreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("PlantillaCorreoId")
                        .HasColumnType("integer");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PlantillaCorreoId");

                    b.ToTable("EventosCorreo", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.LogSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Excepcion")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("Nivel");

                    b.ToTable("LogsSistema", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cantidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Duracion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PrescripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Presentacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.Property<string>("ViaAdministracion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("PrescripcionId");

                    b.ToTable("Medicamentos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FirmaActualizadaEn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirmaImagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Medida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("FechaMedicion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<int>("NinoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Talla")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("MedicoId");

                    b.HasIndex("NinoId", "FechaMedicion")
                        .IsUnique()
                        .HasFilter("\"Eliminado\" = false");

                    b.ToTable("Medidas", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.ToTable("Modulos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Nino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PadreId")
                        .HasColumnType("integer");

                    b.Property<char>("Sexo")
                        .HasColumnType("char(1)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PadreId");

                    b.ToTable("Ninos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.OmsReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EdadMeses")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentil15")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Percentil3")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Percentil50")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Percentil85")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Percentil97")
                        .HasColumnType("decimal(5,2)");

                    b.Property<char>("Sexo")
                        .HasColumnType("char(1)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sexo", "EdadMeses", "Tipo")
                        .IsUnique();

                    b.ToTable("OMS_Referencias", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Opcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Ruta")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("ModuloId");

                    b.ToTable("Opciones", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.OpcionAccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionId")
                        .HasColumnType("integer");

                    b.Property<int>("OpcionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccionId");

                    b.HasIndex("OpcionId", "AccionId")
                        .IsUnique();

                    b.ToTable("OpcionAcciones", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Padre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("MedicoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Padres", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.ParametroSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("Grupo", "Codigo")
                        .IsUnique()
                        .HasFilter("\"Eliminado\" = false");

                    b.ToTable("ParametrosSistema", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.PlantillaCorreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"Eliminado\" = false AND \"Codigo\" IS NOT NULL");

                    b.HasIndex("Eliminado");

                    b.ToTable("PlantillasCorreo", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Prediccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCalculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("FechaObjetivo")
                        .HasColumnType("date");

                    b.Property<int>("NinoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProyeccionMeses")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ValorPredicho")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ValorReal")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("NinoId");

                    b.ToTable("Predicciones", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Prescripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Indicaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<int>("NinoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("Eliminado");

                    b.HasIndex("MedicoId");

                    b.HasIndex("NinoId");

                    b.ToTable("Prescripciones", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Revocado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.ReporteGenerado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("NinoId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UsuarioGeneradorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NinoId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UsuarioGeneradorId");

                    b.HasIndex("Tipo", "FechaGeneracion");

                    b.ToTable("ReportesGenerados", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OpcionAccionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Permitido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpcionAccionId");

                    b.HasIndex("RolId", "OpcionAccionId")
                        .IsUnique();

                    b.ToTable("RolPermisos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.UsuarioEstadoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoNuevo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioQueRealizoCambioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioQueRealizoCambioId");

                    b.ToTable("UsuarioEstadoHistorial", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OpcionAccionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Permitido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpcionAccionId");

                    b.HasIndex("UsuarioId", "OpcionAccionId")
                        .IsUnique();

                    b.ToTable("UsuarioPermisos", (string)null);
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Alimento", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.CategoriaAlimento", "Categoria")
                        .WithMany("Alimentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Cita", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Cita", "CitaOrigen")
                        .WithMany()
                        .HasForeignKey("CitaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SagradaFamilia.Domain.Entities.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Nino", "Nino")
                        .WithMany("Citas")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CitaOrigen");

                    b.Navigation("Medico");

                    b.Navigation("Nino");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Cita", "Cita")
                        .WithOne("Consulta")
                        .HasForeignKey("SagradaFamilia.Domain.Entities.Consulta", "CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Nino", "Nino")
                        .WithMany()
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Medico");

                    b.Navigation("Nino");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.EventoCorreo", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.PlantillaCorreo", "Plantilla")
                        .WithMany()
                        .HasForeignKey("PlantillaCorreoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plantilla");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Medicamento", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Prescripcion", "Prescripcion")
                        .WithMany("Medicamentos")
                        .HasForeignKey("PrescripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescripcion");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Medico", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Medico")
                        .HasForeignKey("SagradaFamilia.Domain.Entities.Medico", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Medida", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Medico", "Medico")
                        .WithMany("Medidas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Nino", "Nino")
                        .WithMany("Medidas")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Nino");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Nino", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Medico", "Medico")
                        .WithMany("Ninos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Padre", "Padre")
                        .WithMany("Ninos")
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Opcion", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Opciones")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.OpcionAccion", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Accion", "Accion")
                        .WithMany("OpcionAcciones")
                        .HasForeignKey("AccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Opcion", "Opcion")
                        .WithMany("OpcionAcciones")
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accion");

                    b.Navigation("Opcion");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Padre", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Medico", "Medico")
                        .WithMany("Padres")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Padre")
                        .HasForeignKey("SagradaFamilia.Domain.Entities.Padre", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Prediccion", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Nino", "Nino")
                        .WithMany("Predicciones")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nino");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Prescripcion", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Consulta", "Consulta")
                        .WithMany("Prescripciones")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Nino", "Nino")
                        .WithMany("Prescripciones")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Medico");

                    b.Navigation("Nino");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.ReporteGenerado", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Nino", "Nino")
                        .WithMany()
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "UsuarioGenerador")
                        .WithMany()
                        .HasForeignKey("UsuarioGeneradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nino");

                    b.Navigation("UsuarioGenerador");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.OpcionAccion", "OpcionAccion")
                        .WithMany("RolPermisos")
                        .HasForeignKey("OpcionAccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OpcionAccion");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.UsuarioEstadoHistorial", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "UsuarioQueRealizoCambio")
                        .WithMany()
                        .HasForeignKey("UsuarioQueRealizoCambioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioQueRealizoCambio");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.HasOne("SagradaFamilia.Domain.Entities.OpcionAccion", "OpcionAccion")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("OpcionAccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SagradaFamilia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcionAccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Accion", b =>
                {
                    b.Navigation("OpcionAcciones");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.CategoriaAlimento", b =>
                {
                    b.Navigation("Alimentos");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Cita", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Consulta", b =>
                {
                    b.Navigation("Prescripciones");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Medidas");

                    b.Navigation("Ninos");

                    b.Navigation("Padres");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Nino", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Medidas");

                    b.Navigation("Predicciones");

                    b.Navigation("Prescripciones");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Opcion", b =>
                {
                    b.Navigation("OpcionAcciones");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.OpcionAccion", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Padre", b =>
                {
                    b.Navigation("Ninos");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Prescripcion", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SagradaFamilia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Medico");

                    b.Navigation("Padre");

                    b.Navigation("Permisos");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
