using Microsoft.EntityFrameworkCore;
using SagradaFamilia.Domain.Entities;
using SagradaFamilia.Domain.Enums;
using SagradaFamilia.Infrastructure.Persistence.Contexts;

namespace SagradaFamilia.Infrastructure.Persistence.Seed
{
    public static class RolAccionSeeder
    {
        public static async Task SeedAsync(AppDbContext context)
        {
            if (!await context.Roles.AnyAsync())
            {
                // Postgres con GENERATED BY DEFAULT AS IDENTITY permite insertar IDs explícitos sin comandos adicionales
                context.Roles.AddRange(
                    new Rol { Id = (int)RolEnum.Administrador, Nombre = nameof(RolEnum.Administrador) },
                    new Rol { Id = (int)RolEnum.Medico, Nombre = nameof(RolEnum.Medico) },
                    new Rol { Id = (int)RolEnum.Padre, Nombre = nameof(RolEnum.Padre) }
                );
                await context.SaveChangesAsync();

                // Resincroniza la secuencia para que el próximo ID autogenerado no colisione
                await context.Database.ExecuteSqlRawAsync(
                    "SELECT setval(pg_get_serial_sequence('\"Roles\"', 'Id'), MAX(\"Id\")) FROM \"Roles\"");
            }

            if (!await context.Acciones.AnyAsync())
            {
                var acciones = Enum.GetNames(typeof(Domain.Enums.Accion))
                    .Select(nombre => new Domain.Entities.Accion { Nombre = nombre });

                context.Acciones.AddRange(acciones);
                await context.SaveChangesAsync();
            }
        }
    }
}